Page({
	data:{
		userInfo:{
			"userbg":"/images/mine/my_bg.png",
			"avatar":"/images/mine/peo.png",
			"name":"习惯简简单单"
		},
		qiandaoImg:{
			"imgurl":"/images/mine/qian1.png"
		},
		minelist:[
			{
				listitems:[
					{
						"icon":"/images/mine/my_diantai_guanzhu.png",
						"text":"我关注的"
					},
					{
						"icon":"/images/mine/my_collect.png",
						"text":"我赞过的"
					},
					{
						"icon":"/images/mine/my_download.png",
						"text":"我的下载"
					},{
						"icon":"/images/mine/my_feed_icon.png",
						"text":"我的话题"
					}
				]
			},
			{
				listitems:[
					{
						"icon":"/images/mine/my_notice.png",
						"text":"通知"
					},
					{
						"icon":"/images/mine/my_message.png",
						"text":"私信"
					}
				]
			},
			{
				listitems:[
					{
						"icon":"/images/mine/my_gift.png",
						"text":"我的礼物"
					},
					{
						"icon":"/images/mine/my_coin.png",
						"text":"我的金币"
					}
				]
			}
			
		]
	},
	toQiandao: function(){
		this.setData({
			qiandaoImg:{
				"imgurl":"/images/mine/qian2.png"
			}
		})
	},
	onLoad:function(){
		console.log("onLoad");
	}
	
})
