Page({
	data:{
		indicatorDots:true,
	    autoplay:true,
	    interval:3000,
	    duration:300,
	    
		banners:[
			"/images/index/zhuanti_img_2.jpg",
	    	"/images/index/zhuanti_img_3.jpg",
	    	"/images/index/zhuanti_img_4.jpg",
	    	"/images/index/zhuanti_img_5.jpg"
		],
		moodlist1:[
			{
				"icon":"/images/find/kuaile.png",
				"text":"快乐"
			},
			{
				"icon":"/images/find/beishang.png",
				"text":"悲伤"
			},
			{
				"icon":"/images/find/gudu.png",
				"text":"孤独"
			}
		],
		moodlist2:[
			{
				"icon":"/images/find/yiqiliao.png",
				"text":"已弃疗"
			},
			{
				"icon":"/images/find/jianya.png",
				"text":"减压"
			},
			{
				"icon":"/images/find/wunai.png",
				"text":"无奈"
			}
		],
		moodlist3:[
			{
				"icon":"/images/find/fanzao.png",
				"text":"烦躁"
			},
			{
				"icon":"/images/find/gandong.png",
				"text":"感动"
			},
			{
				"icon":"/images/find/mimang.png",
				"text":"迷茫"
			}
		],
		sencelist1:[
			{
				"icon":"/images/find/shuiqian.png",
				"text":"睡前"
			},
			{
				"icon":"/images/find/lvxing.png",
				"text":"旅行"
			},
			{
				"icon":"/images/find/sanbu.png",
				"text":"散步"
			}
		],
		sencelist2:[
			{
				"icon":"/images/find/zuoche.png",
				"text":"坐车"
			},
			{
				"icon":"/images/find/duchu.png",
				"text":"独处"
			},
			{
				"icon":"/images/find/shilian.png",
				"text":"失恋"
			}
		],
		sencelist3:[
			{
				"icon":"/images/find/shimian.png",
				"text":"失眠"
			},
			{
				"icon":"/images/find/suibian.png",
				"text":"随便"
			},
			{
				"icon":"/images/find/wuliao.png",
				"text":"无聊"
			}
		],
		speakerlist:[]
	},
	onLoad: function(){
		var that=this;
		wx.request({	
			url:"http://yiapi.xinli001.com/fm/diantai-find-list.json?offset=0&limit=6&key=046b6a2a43dc6ff6e770255f57328f89",
			success: function(res){
				console.log(res.data.data);
				that.setData({
					speakerlist:res.data.data
				})
			}
		});
	}
})
